from django.urls import path
from .import views
urlpatterns = [
path('', views.home, name='home'),
path('home/', views.home, name='home'),
path('register/',views.register,name='register'),
path('login/', views.login, name='login'),
path('logout/', views.logout, name='logout'),
path('profile/', views.profile, name='profile'),
path('edit_profile/', views.edit_profile, name='edit_profile'),
path('userlist/', views.userlist, name='userlist'),
path('deleteuser/<int:id>/', views.deleteuser, name='deleteuser'),
path('add-product/', views.add_product, name='add_product'),
path('products/', views.product_list, name='product_list'),
path('edit-product/<int:id>/', views.edit_product, name='edit_product'),
path('delete-product/<int:id>/', views.delete_product, name='delete_product'),
path('update-quantity/<int:id>/<str:action>/', views.update_quantity, name='update_quantity'),
path('orders/', views.orders, name='orders'),
path('cart/', views.cart, name='cart'),
path('cart/checkout/', views.checkout, name='checkout'),
path('shop/', views.shop, name='shop'),
path('add-to-cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
path('remove-from-cart/<int:id>/', views.remove_from_cart, name='remove_from_cart'),
path('admin-login/',                      views.admin_login,          name='admin_login'),
path('admin-logout/',                     views.admin_logout,         name='admin_logout'),
path('admin-dashboard/',                  views.admin_dashboard,      name='admin_dashboard'),
path('admin-dashboard/add/',              views.admin_add_product,    name='admin_add_product'),
path('admin-dashboard/edit/<int:id>/',    views.admin_edit_product,   name='admin_edit_product'),
path('admin-dashboard/delete/<int:id>/',  views.admin_delete_product, name='admin_delete_product'),
path('review/', views.review_view, name='review'),
path('admin/review/<int:pk>/delete/', views.delete_review, name='admin_delete_review'),
path('chat/', views.chatbot, name='chatbot'),
path('place-order/', views.place_order, name='place_order'),

]